ENCODER_MAP_ENABLE = yes
AUTO_SHIFT_ENABLE = no
SWAP_HANDS_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = yes
MAGIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
MUSIC_ENABLE = no

OLED_ENABLE = yes
OCEAN_DREAM_ENABLE = yes
WPM_ENABLE = yes
SRC += ocean_dream.c
